# Generated by Django 4.2.9 on 2024-02-09 10:49

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('ingredients', models.TextField(max_length=10000)),
                ('instructions', models.TextField(max_length=10000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(choices=[('chicken', 'Chicken'), ('fish', 'Fish'), ('meat', 'Meat'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pasta', 'Pasta'), ('seafood', 'Seafood'), ('salad', 'Salad'), ('soup', 'Soup'), ('sandwich', 'Sandwich'), ('breakfast', 'Breakfast'), ('dessert', 'Dessert')], default='vegan', max_length=50)),
                ('effort', models.CharField(choices=[('bad_day_comfort_food', 'Bad day comfort food'), ('trying_a_healthy_day', 'Trying a healthy day'), ('im_in_a_hurry', "I'm in a hurry"), ('i_have_time_but_no_brains', 'I have time but no brains'), ('to_far_until_payday', 'To far until payday')], default='Bad day comfort food', max_length=50)),
                ('food_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('image_alt', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciperating', models.IntegerField()),
                ('recipepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.recipepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('recipepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.recipepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
