# Generated by Django 4.2.9 on 2024-01-30 10:46

from django.db import migrations, models
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recipepost_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='recipepost',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='recipepost',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='placeholder', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='recipes/'),
        ),
        migrations.AddField(
            model_name='recipepost',
            name='ingredients',
            field=djrichtextfield.models.RichTextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='recipepost',
            name='instructions',
            field=djrichtextfield.models.RichTextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='effort',
            field=models.CharField(choices=[('bad_day_comfort_food', 'Bad day comfort food'), ('trying_a_healthy_day', 'Trying a healthy day'), ('im_in_a_hurry', "I'm in a hurry"), ('i_have_time_but_no_brains', 'I have time but no brains'), ('to_far_until_payday', 'To far until payday')], default='Bad day comfort food', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='meal_type',
            field=models.CharField(choices=[('chicken', 'Chicken'), ('fish', 'Fish'), ('meat', 'Meat'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pasta', 'Pasta'), ('seafood', 'Seafood'), ('salad', 'Salad'), ('soup', 'Soup'), ('sandwich', 'Sandwich'), ('breakfast', 'Breakfast'), ('dessert', 'Dessert')], default='vegan', max_length=50),
        ),
    ]
