# Generated by Django 4.2.9 on 2024-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_recipepost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='ingredients',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='instructions',
            field=models.TextField(max_length=10000),
        ),
    ]
