# Generated by Django 4.2.9 on 2024-01-30 11:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_recipepost_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='image',
        ),
        migrations.AddField(
            model_name='recipepost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
