# Generated by Django 4.2.9 on 2024-02-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_reciperating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipepost',
            old_name='featured_image',
            new_name='food_image',
        ),
    ]
