# Generated by Django 4.2.9 on 2024-02-05 16:38

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_featured_image_recipepost_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='ingredients',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='instructions',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
