# Generated by Django 4.2.9 on 2024-02-05 16:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_recipepost_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='food_image_resized',
            field=django_resized.forms.ResizedImageField(crop=None, default='placeholder', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='recipes/'),
        ),
    ]
