# Generated by Django 4.2.9 on 2024-02-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_recipepost_food_image_resized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='food_image_resized',
        ),
    ]
