# Generated by Django 4.2.9 on 2024-02-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='ingredients',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='instructions',
            field=models.TextField(max_length=10000),
        ),
    ]
